---
abstract: 'Get the values for webcolours'
author:
  - 'Kevin Mulholland <moodfarm@cpan.org>'
build_requires:
  Test::More: 0
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebColors
requires:
  Exporter: 0
  perl: v5.10.0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://github.com/moodfarm/webcolors/issues
  repository: https://github.com/moodfarm/WebColors
version: 0.2.0
